## configuration file for running EVC

# EVC가 수행할 작업
activation: gradio # "train" or "pred" or "gradio"
# 클러스터 그룹명
group:
  - &group1 keti_nuc
  - &group2 keti_rpi
  - &group3 keti_server
# 작업을 수행할 노드
target:
#   *group1:
#   -   name: n01
#       ip: evc.re.kr
#       port: 33312
#       hw: intel_NUC
#       os: ubuntu
#       gpu: RTX2080
    
#   -   name: n02
#       ip: evc.re.kr
#       port: 33322
#       hw: intel_NUC
#       os: ubuntu
#       gpu: RTX2080

  *group2:
  -   name: rpi6402
      ip: evc.re.kr
      port: 39002
      hw: RPI
      os: linux
      gpu: None

#   -   name: rpi6403
#       ip: evc.re.kr
#       port: 39003
#       hw: RPI
#       os: linux
#       gpu: None
  
#   *group3:
#   -   name: p02
#       ip: evc.re.kr
#       port: 20023
#       hw: intel_Server
#       os: ubuntu
#       gpu: RTX4090

# 노드 소유자 명
owner: keti # host name

## AI 모델 정보
# 모델 이름
model_name: selective-run-test # your_model
# 모델 버전
version: "1.2"
# 모델이 수행하는 태스크
task: detection # i.e. classification, segmentation
# 학습 혹은 추론 대상 데이터
data: None